"""
PDF Report Generator for NanoVox

Generates a branded one-page (or multi-page) PDF report for a single
analyzed call, including scores, commitment status, and full transcript.
"""
import io
import json
import logging
from datetime import datetime
from fpdf import FPDF

logger = logging.getLogger(__name__)


class NanoVoxReport(FPDF):
    """Custom PDF with NanoVox branding."""

    def header(self):
        # Brand bar
        self.set_fill_color(99, 102, 241)  # Indigo gradient-start
        self.rect(0, 0, 210, 12, 'F')
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(255, 255, 255)
        self.set_y(2)
        self.cell(0, 8, 'NanoVox', align='L')
        self.set_font('Helvetica', '', 9)
        self.cell(0, 8, 'Call Quality Report', align='R')
        self.ln(12)

    def footer(self):
        self.set_y(-12)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f'Generated by NanoVox | Page {self.page_no()}', align='C')


def _score_color(score: float) -> tuple:
    """Return RGB tuple based on score range."""
    if score >= 80:
        return (34, 197, 94)   # Green
    elif score >= 60:
        return (234, 179, 8)   # Yellow
    else:
        return (239, 68, 68)   # Red


def _commitment_color(status: str) -> tuple:
    """Return RGB tuple based on commitment status."""
    if status in ('Committed', 'Resolved'):
        return (34, 197, 94)
    elif status in ('Ghosted/Uncommitted', 'Likely unresolved'):
        return (239, 68, 68)
    else:
        return (234, 179, 8)


def generate_report(call_data: dict) -> bytes:
    """
    Generate a PDF report for a single analyzed call.

    Args:
        call_data: Full call dict from get_call_detail()

    Returns:
        PDF file as bytes
    """
    pdf = NanoVoxReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Parse stored JSON if needed
    analysis = call_data.get("analysis_json", {})
    if isinstance(analysis, str):
        try:
            analysis = json.loads(analysis)
        except (json.JSONDecodeError, TypeError):
            analysis = {}

    transcript_data = call_data.get("transcript_json", {})
    if isinstance(transcript_data, str):
        try:
            transcript_data = json.loads(transcript_data)
        except (json.JSONDecodeError, TypeError):
            transcript_data = {}

    breakdown = analysis.get("breakdown", {})
    transcript_segments = transcript_data.get("transcript", [])

    # ── Section 1: Report Header Info ──
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(120, 120, 120)

    analyzed_at = call_data.get("analyzed_at", "")
    try:
        dt = datetime.fromisoformat(analyzed_at.replace("Z", "+00:00"))
        date_str = dt.strftime("%B %d, %Y at %I:%M %p")
    except (ValueError, AttributeError):
        date_str = analyzed_at

    pdf.cell(0, 5, f'Date: {date_str}', ln=True)
    pdf.cell(0, 5, f'File: {call_data.get("filename", "Unknown")}', ln=True)
    pdf.cell(0, 5, f'Profile: {call_data.get("profile_used", "Sales")}', ln=True)
    duration = call_data.get("call_duration", 0)
    if duration:
        mins = int(duration // 60)
        secs = int(duration % 60)
        pdf.cell(0, 5, f'Duration: {mins}m {secs}s  |  Segments: {call_data.get("segment_count", 0)}', ln=True)
    pdf.ln(4)

    # ── Section 2: Overall Score (big, centered) ──
    final_score = call_data.get("final_score", 0) or 0
    score_color = _score_color(final_score)

    pdf.set_font('Helvetica', 'B', 36)
    pdf.set_text_color(*score_color)
    pdf.cell(0, 18, f'{final_score:.0f}/100', align='C', ln=True)

    # Score label
    if final_score >= 85:
        label = "Excellent"
    elif final_score >= 70:
        label = "Good"
    elif final_score >= 55:
        label = "Fair"
    else:
        label = "Needs Improvement"

    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, label, align='C', ln=True)

    # Interpretation
    interpretation = call_data.get("interpretation") or analysis.get("interpretation", "")
    if interpretation:
        pdf.set_font('Helvetica', 'I', 8)
        pdf.set_text_color(130, 130, 130)
        pdf.multi_cell(0, 4, interpretation, align='C')
    pdf.ln(4)

    # ── Section 3: Commitment Status Badge ──
    commitment_status = call_data.get("commitment_status", "Unknown")
    commit_color = _commitment_color(commitment_status)

    pdf.set_fill_color(*commit_color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 10)

    badge_text = f'  Commitment: {commitment_status}  '
    badge_width = pdf.get_string_width(badge_text) + 8
    x_start = (210 - badge_width) / 2
    pdf.set_x(x_start)
    pdf.cell(badge_width, 8, badge_text, fill=True, ln=True)
    pdf.ln(5)

    # ── Section 4: Parameter Scores Table ──
    pdf.set_text_color(50, 50, 50)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, 'Parameter Scores', ln=True)
    pdf.ln(1)

    # Table header
    pdf.set_fill_color(240, 240, 245)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(65, 7, 'Parameter', border='B', fill=True)
    pdf.cell(30, 7, 'Score', border='B', fill=True, align='C')
    pdf.cell(30, 7, 'Penalty', border='B', fill=True, align='C')
    pdf.cell(60, 7, 'Context', border='B', fill=True)
    pdf.ln()

    # Table rows
    params = [
        ("Talk Ratio", "talk_ratio"),
        ("Sentiment", "sentiment"),
        ("Empathy", "empathy"),
        ("Commitment", "resolution"),
    ]

    pdf.set_font('Helvetica', '', 9)
    for display_name, key in params:
        param = breakdown.get(key, {})
        score = param.get("score", 0) or 0
        penalty = param.get("penalty", 0) or 0
        metadata = param.get("metadata", {})
        context = metadata.get("context_text", "")

        # Score color
        pdf.set_text_color(50, 50, 50)
        pdf.cell(65, 7, display_name, border='B')

        sc = _score_color(score)
        pdf.set_text_color(*sc)
        pdf.cell(30, 7, f'{score:.0f}', border='B', align='C')

        pdf.set_text_color(180, 80, 80) if penalty > 30 else pdf.set_text_color(100, 100, 100)
        pdf.cell(30, 7, f'{penalty:.0f}', border='B', align='C')

        pdf.set_text_color(100, 100, 100)
        # Truncate context if too long
        if len(context) > 35:
            context = context[:32] + '...'
        pdf.cell(60, 7, context, border='B')
        pdf.ln()

    pdf.ln(5)

    # ── Section 5: Full Transcript ──
    if transcript_segments:
        pdf.set_text_color(50, 50, 50)
        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(0, 7, f'Transcript ({len(transcript_segments)} segments)', ln=True)
        pdf.ln(2)

        for seg in transcript_segments:
            speaker = seg.get("speaker", "Unknown")
            text = seg.get("text", "")
            start = seg.get("start", 0)

            # Timestamp
            mins = int(start // 60)
            secs = int(start % 60)
            ts = f'[{mins:02d}:{secs:02d}]'

            # Speaker styling
            if speaker == "Agent":
                pdf.set_text_color(99, 102, 241)  # Indigo
                pdf.set_font('Helvetica', 'B', 8)
            else:
                pdf.set_text_color(139, 92, 246)   # Purple
                pdf.set_font('Helvetica', 'B', 8)

            pdf.cell(25, 5, f'{ts} {speaker}:')

            # Text
            pdf.set_text_color(60, 60, 60)
            pdf.set_font('Helvetica', '', 8)

            # Handle long text with multi_cell
            remaining_width = 210 - 25 - 20  # page width - label - margins
            x_pos = pdf.get_x()
            y_pos = pdf.get_y()
            pdf.multi_cell(remaining_width, 4, text)

            # Small gap between segments
            pdf.ln(1)

    # Output as bytes
    return pdf.output()
